//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver
{
    using System;
    using System.Collections.Generic;
using ProtoBuf;
    
    [Serializable]
    [ProtoContract]
    public partial class Consumer
    {
        [ProtoMember(1)]
        public int ID { get; set; }

        [ProtoMember(2)]
        public Nullable<System.Guid> AspNetUserID { get; set; }

        [ProtoMember(3)]
        public int OrganizationID { get; set; }
        [ProtoMember(4)]
        public int GenderID { get; set; }
        [ProtoMember(5)]
        public Nullable<int> NamePrefixID { get; set; }
        [ProtoMember(6)]
        public string FirstName { get; set; }
        [ProtoMember(7)]
        public string MiddleName { get; set; }
        [ProtoMember(8)]
        public string LastName { get; set; }
        [ProtoMember(9)]
        public Nullable<int> NameSuffixID { get; set; }
        [ProtoMember(10)]
        public System.DateTime BirthDate { get; set; }
        [ProtoMember(11)]
        public System.DateTime OriginalHireDate { get; set; }
        [ProtoMember(12)]
        public Nullable<int> MaritalStatusID { get; set; }
        [ProtoMember(13)]
        public bool IsTestUser { get; set; }
        [ProtoMember(14)]
        public Nullable<System.DateTime> TestUserStartDate { get; set; }
        [ProtoMember(15)]
        public Nullable<System.DateTime> TestUserExpirationDate { get; set; }
        [ProtoMember(16)]
        public bool Deleted { get; set; }
        [ProtoMember(17)]
        public Nullable<System.DateTime> CurrentHireDate { get; set; }
        [ProtoMember(18)]
        public Nullable<System.DateTime> AllowedAccessDate { get; set; }
        [ProtoMember(19)]
        public System.Guid ExternalId { get; set; }
    }
}
