//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        public int ID { get; set; }
        public Nullable<System.Guid> AspNetUserID { get; set; }
        public int OrganizationID { get; set; }
        public int GenderID { get; set; }
        public Nullable<int> NamePrefixID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> NameSuffixID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime OriginalHireDate { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public bool IsTestUser { get; set; }
        public Nullable<System.DateTime> TestUserStartDate { get; set; }
        public Nullable<System.DateTime> TestUserExpirationDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CurrentHireDate { get; set; }
        public Nullable<System.DateTime> AllowedAccessDate { get; set; }
        public System.Guid ExternalId { get; set; }
    }
}
