//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int VendorID { get; set; }
        public int ProductTypeID { get; set; }
        public Nullable<int> ProductSubTypeID { get; set; }
        public string Code { get; set; }
        public string InternalName { get; set; }
        public string ExternalShortName { get; set; }
        public string ExternalFullName { get; set; }
        public bool Locked { get; set; }
        public bool Deleted { get; set; }
        public string InternalDescription { get; set; }
        public string ExternalDescription { get; set; }
        public string ExternalDescriptionWmd { get; set; }
    }
}
